# Generated by Django 5.1.7 on 2025-03-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("opponent", models.CharField(max_length=100)),
                ("goals", models.IntegerField(default=0)),
                ("assists", models.IntegerField(default=0)),
                ("final_score", models.CharField(max_length=20)),
                (
                    "media",
                    models.FileField(blank=True, null=True, upload_to="game_media/"),
                ),
            ],
        ),
    ]
