# Generated by Django 5.1.7 on 2025-04-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["-date"]},
        ),
    ]
